# --- Stage 1: Build the project ---
    FROM node:18 AS builder
    WORKDIR /app
    
    COPY package*.json ./
    RUN npm install
    
    COPY . .
    RUN npm run build
    
    # בשלב זה נוצרה התיקייה dist בתוך הקונטיינר
    